spring:
  application:
    name: bugtrack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bugtrack 
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
       
    
server:
  port: 8080
  
bugtrack:
  loaddata: true  
    